### ISSUE TITLE
Guild Ranking Leader

### ISSUE THREAD

**Issue by MediaWorld** [kokspflanze/PServerRanking#1]
It will be pretty nice if you can add the Information on top with the Leader of a guild.

Maybe here: http://prntscr.com/ekkr12

**Comment by kokspflanze** [comment]
added with https://github.com/kokspflanze/PServerSRO/commit/5dd4780db7428590cf46fce80ca63c6b6762785f

will be online with the next stable release.

btw also the sort of the members depends on the memberClass, so the owner it everytime on the first position.
